name: Build API image

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - 'app/*'
      - 'pnpm-lock.yaml'
  # Allow manual trigger
  workflow_dispatch:
concurrency:
  group: 'app'
  cancel-in-progress: true

jobs:
  build: # This will suppress any download message and remove the 600 sec timout
    # time:

    runs-on: ubuntu-latest
    #env variables
    env:
      NOW: ''
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            commit_sha=${{ github.sha }}
            built_at=${{env.NOW}}
          tags: |
            ghcr.io/adamhancock/bolt.diy/app:${{ github.sha }}
            ghcr.io/adamhancock/bolt.diy/app:dev
